### ISSUE TITLE
PRIORIDADE - 2.1:Criar novos campos + filtros ...no painelGabinete.

### ISSUE THREAD

**Issue by leilacarvalho-git** [interlegis/sigi#27]
Em Convênios, painel "Acompanhamento no Gabinete", adicionar logo no INÍCIO os seguintes campos:
1-adicionar o campo "**data do email de solicitação**" **(+filtro).**
2-migrar para a 2a posição o campo "data de cadastro no Sigad". (já tem filtro)
3-criar um dropdown para **"Inclui produtos/serviços?"**. **(+filtro)**.

**Comment by sesostris** [comment]
Nova configuração do painel "Acompanhamento no gabinete"
----------------------------------------------------------------------------------

* Passar o campo DATA_SIGAD para dentro do painel do gabinete
* Adicionar DATA E-MAIL SOLICITAÇÃO (com filtro)
* Adicionar campo dropdown INCLUI PRODUTOS / SERVIÇOS

Ordem dos campos:
---------------------------
* Data de e-mail de solicitação
* Data de cadastro no SIGAD
* Inclui produtos / serviços
* Estado atual
* Acompanhado por
* Observações
