### ISSUE TITLE
PRIORIDADE - 2.6:ERRO ao gerar RELATÓRIO a partir dos registros exportados para o CARRINHO.

### ISSUE THREAD

**Issue by leilacarvalho-git** [interlegis/sigi#30]
Boa noite, Sesóstris!

Tudo bem?

Primeiro a boa notícia: o colega Anderson/Coadfi já fez o cadastro de vários registros de convênios deles 
após vc disponibilizar a última versão!!!! Acredita??? Mt legal, né?

Hoje à tarde, ele contactou-me para relatar um probleminha ao gerar relatórios a partir de registros
exportados para o Carrinho. Eu nem sabia como se fazia isso, e ele - gentilmente - me ensinou.rss...

Só agora à noite tive tempo para reproduzir os passos e entender o problema.

Vamos aos itens:
1)PROBLEMA:nos Convênios, quando filtramos por "Protocolo", são encontrados 20 registros. No entanto, 
quando geramos o Relatório, **somente aparece UM registro.**  No CSV, aparecem todos os 20regs. Vide anexos.
**Estranhamente, quando filtramos por "ACT", tudo funciona bem.rss... 

2)AJUSTE:ele perguntou se poderia mudar o título do relatório: para "Relatório de PARCERIAS...", em vez de 
"Relatório de Convênios", para ficar mais abrangente. Achei super válido!

3)MELHORIA:pensei aqui comigo, e se não for pedir demais: seria possível deixar que o user escrevesse o título 
desejado para o relatório?? Podemos deixar um título default. Se o user não gostar, pode alterar ou até mudar 
completamente. Que tal??

-Se vc conseguir corrigir o problema até 2a-feira(itens 1 e 2), será ótimo! O colega Anderson deve precisar
dessa listagem correta. Se necessário, podemos sacrificar algum dos nossos itens (2.1 a 2.5), priorizando 
a correção, ok?
-Quanto ao item 3, podemos abrir um outro tkt e colocar na fila de prioridades. 

Desde já, mttt obrigada e bom trabalho.

---------------------------------------
[RelatorioDeProtocolos.pdf](https://github.com/interlegis/sigi/files/6321805/RelatorioDeProtocolos.pdf)
[RelatorioDeACTs.pdf](https://github.com/interlegis/sigi/files/6321806/RelatorioDeACTs.pdf)
![Screen Shot 2021-04-15 at 21 35 26](https://user-images.githubusercontent.com/81989707/114956570-882c6c00-9e35-11eb-8ba6-f6af05a89eee.png)
![Screen Shot 2021-04-15 at 21 44 03](https://user-images.githubusercontent.com/81989707/114956602-9b3f3c00-9e35-11eb-83b5-f7f0c84d7cdc.png)
[conveniosProtocolos.csv](https://github.com/interlegis/sigi/files/6321825/conveniosProtocolos.csv)

**Comment by sesostris** [comment]
Leila, não entendi como se filtra por "Protocolo". Os filtros disponíveis são por estado atual, acompanhado por, projeto, tipo, conveniada, equipada e UF. Como faz para filtrar por protocolo?
