### ISSUE TITLE
PRIORIDADE - 15:Criar 2 campos: SIGLA (do Órgão) & GestorOuFiscalTecnico (do Convênio).

### ISSUE THREAD

**Issue by leilacarvalho-git** [interlegis/sigi#33]
**Sesóstris, por favor, criar DOIS novos CAMPOS:
1)textfield de SIGLA do ORGAO, com tamanho 25.=
2)dropdown de GestorOuFiscalTecnico do CONVENIO (servidores ou áreas???)
*Estou discutindo esse assunto com Anderson/Coadfi e Natália/Sadcon.
Cfe conversei hoje com o colega Anderson/Coadfi, ele me disse que agora esse gestor é uma área do ILB(Scco), 
e não uma pessoa, cfe aprovado pela Dger. E quem seria o substituto, pois não vi isso na Portaria?
![WhatsApp Image 2021-04-19 at 11 32 18](https://user-images.githubusercontent.com/81989707/115290885-7515e680-a12a-11eb-9dfe-988c1d678a05.jpeg)

--------------------** 

**===============================================================
-DILEMA: tentar encontrar regs DUPLICADOS pela SIGLA ou pelo CNPJ??
https://github.com/interlegis/sigi/issues/25
===============================================================**

![CAMPO_GESTOR_OU_FISCAL_TECNICO](https://user-images.githubusercontent.com/81989707/115163638-99b58400-a080-11eb-8984-c2f4fc92c27e.png)

**Comment by sesostris** [comment]
Atendido pelos commits 17ae196 e 883e15b
