### ISSUE TITLE
PRIORIDADE - 25:Nas Oficinas, tratar Membros da equipe:INTERNOS não listados (bug?) e EXTERNOS (ainda não existentes). 

### ISSUE THREAD

**Issue by leilacarvalho-git** [interlegis/sigi#55]
Sesóstris, cfe conversamos hoje (29/04/21), por favor adicionar TRÊS novos campos:
1)checkbox de "é usuário externo".
2)órgão de origem do usuário.
3)qualificações do usuário (Ex:Doutor em Assinatura Digital pelo MIT).
....................
Sesóstris, 

a colega Maria/Coperi está cadastrando manualmente as Oficinas e se deparou hoje(27/04) com 2 situações: 
1)a consultora do Senado (**Helena Assaf**) não aparece no dropdown p ser escolhida como Membro da equipe. 
De onde vêm os Membros, por favor? Isso é bug... ou ali constam apenas os servidores do Interlegis/ILB?

2)Noutra Oficina de Assinatura Digital, Maria precisará cadastrar na equipe um Membro externo (como instrutor), 
que é da CM de Itapoá.  Nos dropdowns, são todos servidores??
Talvez a saída seja criarmos uma outra grid de membros externos. Apenas textfields ou com tabela/relacionamentos?? 
O que vc acha ou sugere?? 
_Eu disse à Maria para ir adiantando os cadastros dos membros internos, pois trataremos as Oficinas assim que 
terminarmos as demandas urgentes da carga de CMs/Ass, ok?_

![Screen Shot 2021-04-27 at 18 36 09](https://user-images.githubusercontent.com/81989707/116316218-fc490700-a787-11eb-9505-c3473ad2e866.png)

**Comment by sesostris** [comment]
Leila solicitou que fossem acrescentados os seguintes campos no model servidores.Servidor:

* colaborador externo: campo booleano que indica se o colaborador é de algum órgão externo
* órgão de origem: nome do órgão de origem do colaborador externo
* qualificações: textfield para serem informadas as qualificações do colaborador externo
