### ISSUE TITLE
PRIORIDADE - 99.1:no Menu Tabelas Auxiliares, adicionar todas as tabelas básicas do sistema.

### ISSUE THREAD

**Issue by leilacarvalho-git** [interlegis/sigi#70]
No Menu Tabelas Auxiliares:
1)fazer o levantamento das tabelas de "tipos" em todo o sistema.
2)colocar todas essas tabelas básicas no Menu Tabelas Auxiliares.

*Isso para facilitar manutenção (exclusão e alteração) de registros auxiliares.
*Atualmente, nem todas as tabelas auxiliares estão no menu.

**Comment by luderibeiro** [comment]
Encontramos alguns registros como "Tipo de Solicitação" mas preferímos não deixa-los editáveis o que fecha essa Issue sem modificações.
