### ISSUE TITLE
PRIORIDADE - 99.2: Na Listagem de CONVÊNIOS, ordenar por ÓrgãoConveniado + Status +DataConveniada(reverseOrder).

### ISSUE THREAD

**Issue by leilacarvalho-git** [interlegis/sigi#72]
Para facilitar a consulta pelos colegas do Gabinete, da Central de Atendimento e dos Gerentes Interlegis,
por favor, **ordenar a Listagem de CONVÊNIOS por 3 campos** ao mesmo tempo: ÓrgãoConveniado + Status(Vigente,Pendente,Vencido) + DataConveniada(reverseOrder).

![Screen Shot 2021-07-16 at 20 03 28](https://user-images.githubusercontent.com/81989707/126016303-11ea1c8c-8e7c-4260-8d9b-bc356119f77d.png)

**Comment by leilacarvalho** [comment]
@Lude, se não for possível ainda usar o campo "Status", pode ordenar os registros APENAS considerando:
ÓrgãoConveniado (ascendente) + DtInicioVigencia(reverseOrder), ok?
*DtInicioVigencia = DtConveniada.
