### ISSUE TITLE
PRIORIDADE - 00.00:Nos Convênios, suprimir 3 campos e respectivos filtros do painel controle/Gabinete.

### ISSUE THREAD

**Issue by leilacarvalho-git** [interlegis/sigi#79]
Suprimir os 3 CAMPOS e seus respectivos FILTROS.
Eles são derivados da planilha de controle do Gabinete. No entanto, acabamos não usando e ficam defasados.

![Screen Shot 2021-08-04 at 15 42 25](https://user-images.githubusercontent.com/81989707/128237221-4ad49855-d200-46ac-8ce9-127ef3752d38.png)
![Screen Shot 2021-08-04 at 15 49 22](https://user-images.githubusercontent.com/81989707/128237998-6de33940-1b08-4a17-ba10-4cb580b03a6a.png)

![Screen Shot 2021-08-04 at 15 46 58](https://user-images.githubusercontent.com/81989707/128237683-d360de1f-5f81-4c17-80b0-cea61d183de9.png)

**Comment by leilacarvalho** [comment]
Na listagem, tb SUPRIMIR os dois campos: "Estado atual" e "Acompanhado por". 
![Screen Shot 2021-08-05 at 12 10 56](https://user-images.githubusercontent.com/40795096/128374566-3cc49843-107d-4285-8d9d-499c92d48b08.png)
